In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/AncaAl/CO2_emission/main/CO2_emission.csv")
df

,Model_Year,Make,Model,Vehicle_Class,Engine_Size,Cylinders,Transmission,Fuel_Consumption_in_City(L/100 km),Fuel_Consumption_in_City_Hwy(L/100 km),Fuel_Consumption_comb(L/100km),CO2_Emissions,Smog_Level
0,2021,Acura,ILX,Compact,2.4,4,AM8,9.9,7.0,8.6,199,3
1,2021,Acura,NSX,Two-seater,3.5,6,AM9,11.1,10.8,11.0,256,3
2,2021,Acura,RDX SH-AWD,SUV: Small,2.0,4,AS10,11.0,8.6,9.9,232,6
3,2021,Acura,RDX SH-AWD A-SPEC,SUV: Small,2.0,4,AS10,11.3,9.1,10.3,242,6
4,2021,Acura,TLX SH-AWD,Compact,2.0,4,AS10,11.2,8.0,9.8,230,7
...,...,...,...,...,...,...,...,...,...,...,...,...
930,2021,Volvo,XC40 T5 AWD,SUV: Small,2.0,4,AS8,10.7,7.7,9.4,219,5
931,2021,Volvo,XC60 T5 AWD,SUV: Small,2.0,4,AS8,11.1,8.3,9.9,230,5
932,2021,Volvo,XC60 T6 AWD,SUV: Small,2.0,4,AS8,11.7,8.6,10.3,240,7
933,2021,Volvo,XC90 T5 AWD,SUV: Standard,2.0,4,AS8,11.5,8.4,10.1,236,5
934,2021,Volvo,XC90 T6 AWD,SUV: Standard,2.0,4,AS8,12.1,8.5,10.5,245,7

### Clean & get familar with DataSet

In [5]:
df.shape

(935, 12)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 935 entries, 0 to 934
Data columns (total 12 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   Model_Year                              935 non-null    int64
 1   Make                                    935 non-null    object
 2   Model                                   935 non-null    object
 3   Vehicle_Class                           935 non-null    object
 4   Engine_Size                             935 non-null    float64
 5   Cylinders                               935 non-null    int64
 6   Transmission                            935 non-null    object
 7   Fuel_Consumption_in_City(L/100 km)      935 non-null    float64
 8   Fuel_Consumption_in_City_Hwy(L/100 km)  935 non-null    float64
 9   Fuel_Consumption_comb(L/100km)          935 non-null    float64
 10  CO2_Emissions                           935 non-null    int64
 11  Smog_Level                              935 non-null    int64
dtypes: float64(4), int64(4), object(4)
memory usage: 87.8+ KB

In [7]:
#Check for missing values
df.isna().any()

Model_Year                                False
Make                                      False
Model                                     False
Vehicle_Class                             False
Engine_Size                               False
Cylinders                                 False
Transmission                              False
Fuel_Consumption_in_City(L/100 km)        False
Fuel_Consumption_in_City_Hwy(L/100 km)    False
Fuel_Consumption_comb(L/100km)            False
CO2_Emissions                             False
Smog_Level                                False
dtype: bool

In [8]:
df.isna().sum()

Model_Year                                0
Make                                      0
Model                                     0
Vehicle_Class                             0
Engine_Size                               0
Cylinders                                 0
Transmission                              0
Fuel_Consumption_in_City(L/100 km)        0
Fuel_Consumption_in_City_Hwy(L/100 km)    0
Fuel_Consumption_comb(L/100km)            0
CO2_Emissions                             0
Smog_Level                                0
dtype: int64

In [9]:
df['Model'].unique()

array(['ILX', 'NSX', 'RDX SH-AWD', 'RDX SH-AWD A-SPEC', 'TLX SH-AWD',
       'TLX SH-AWD A-SPEC', 'Giulia', 'Giulia AWD', 'Giulia Quadrifoglio',
       'Stelvio', 'Stelvio AWD', 'Stelvio AWD Quadrifoglio', 'DB11 V8',
       'DB11 AMR', 'DBS Superleggera', 'DBX V8', 'Vantage V8',
       'A4 allroad 45 TFSI quattro', 'A4 Sedan 40 TFSI quattro',
       'A4 Sedan 45 TFSI quattro', 'A5 Cabriolet 45 TFSI quattro',
       'A5 Coupe 45 TFSI quattro', 'A5 Sportback 45 TFSI quattro',
       'A6 allroad 55 TFSI quattro', 'A6 Sedan 45 TFSI quattro',
       'A6 Sedan 55 TFSI quattro', 'A7 Sportback 55 TFSI quattro',
       'A8 L Sedan 55 TFSI quattro', 'A8 L Sedan 60 TFSI quattro',
       'Q3 40 TFSI quattro', 'Q3 45 TFSI quattro', 'Q5 45 TFSI quattro',
       'Q5 Sportback 45 TFSI quattro', 'Q7 45 TFSI quattro',
       'Q7 55 TFSI quattro', 'Q8 55 TFSI quattro', 'R8 Coupe',
       'R8 Coupe quattro', 'R8 Spyder', 'R8 Spyder quattro',
       'RS 5 Coupe quattro', 'RS 5 Sportback quattro',
       'RS 6 Avant quattro', 'RS 7 Sportback quattro', 'RS Q8 quattro',
       'S4 Sedan quattro', 'S5 Cabriolet quattro', 'S5 Coupe quattro',
       'S5 Sportback quattro', 'S6 Sedan quattro', 'S7 Sportback quattro',
       'S8 Sedan quattro', 'SQ5 quattro', 'SQ5 Sportback quattro',
       'SQ7 quattro', 'SQ8 quattro', 'TT Coupe 45 TFSI quattro',
       'TT Roadster 45 TFSI quattro', 'TT RS Coupe quattro',
       'TTS Coupe quattro', 'Bentayga', 'Continental GT',
       'Continental GT Convertible', 'Flying Spur',
       '228i xDrive Gran Coupe', '230i xDrive Cabriolet',
       '230i xDrive Coupe', '330i xDrive Sedan', '430i xDrive Coupe',
       '530i xDrive Sedan', '540i xDrive Sedan', '750i xDrive Sedan',
       '750Li xDrive Sedan', 'Alpina B7 xDrive', 'Alpina XB7',
       'M2 Competition', 'M235i xDrive Gran Coupe',
       'M240i xDrive Cabriolet', 'M240i xDrive Coupe',
       'M340i xDrive Sedan', 'M440i xDrive Coupe', 'M5 Sedan',
       'M5 Competition', 'M550i xDrive Sedan', 'M760i xDrive Sedan',
       'M8 Cabriolet', 'M8 Cabriolet Competition', 'M8 Coupe',
       'M8 Coupe Competition', 'M8 Gran Coupe',
       'M8 Gran Coupe Competition', 'M850i xDrive Cabriolet',
       'M850i xDrive Coupe', 'M850i xDrive Gran Coupe', 'X1 xDrive28i',
       'X2 xDrive28i', 'X2 M35i', 'X3 xDrive30i', 'X3 M',
       'X3 M Competition', 'X3 M40i', 'X4 xDrive30i', 'X4 M',
       'X4 M Competition', 'X4 M40i', 'X5 xDrive40i', 'X5 M',
       'X5 M Competition', 'X5 M50i', 'X6 xDrive40i', 'X6 M',
       'X6 M Competition', 'X6 M50i', 'X7 xDrive40i', 'X7 M50i',
       'Z4 sDrive30i', 'Z4 M40i', 'Chiron', 'Chiron Pur Sport', 'Enclave',
       'Enclave AWD', 'Encore', 'Encore (SIDI)', 'Encore AWD',
       'Encore AWD (SIDI)', 'Encore GX', 'Envision', 'Envision AWD',
       'CT4', 'CT4 AWD', 'CT4-V', 'CT4-V AWD', 'CT5', 'CT5 AWD', 'CT5-V',
       'CT5-V AWD', 'Escalade 4WD', 'Escalade 4WD (Without Stop-Start)',
       'XT4', 'XT4 AWD', 'XT5', 'XT5 AWD', 'XT6 AWD', 'Blazer',
       'Blazer AWD', 'Camaro', 'Camaro SS', 'Camaro ZL1', 'Colorado',
       'Colorado 4WD', 'Colorado ZR2 4WD', 'Corvette', 'Equinox',
       'Equinox AWD', 'Malibu', 'Silverado', 'Silverado Custom/WT',
       'Silverado (Without AFM)', 'Silverado FFV',
       'Silverado (Without DFM)', 'Silverado 4WD',
       'Silverado 4WD Custom/WT', 'Silverado 4WD Trail Boss',
       'Silverado 4WD (Without AFM)', 'Silverado 4WD FFV',
       'Silverado 4WD Trail Boss (Without AFM)',
       'Silverado 4WD (Without DFM)',
       'Silverado 4WD (Without Stop-Start)',
       'Silverado 4WD Trail Boss (Without Stop-Start)', 'Spark',
       'Suburban', 'Suburban (Without Stop-Start)', 'Suburban 4WD',
       'Suburban 4WD (Without Stop-Start)', 'Tahoe',
       'Tahoe (Without Stop-Start)', 'Tahoe 4WD',
       'Tahoe 4WD (Without Stop-Start)', 'Trailblazer', 'Trailblazer AWD',
       'Traverse', 'Traverse AWD', 'Trax', 'Trax (SIDI)', 'Trax 4WD',
       'Trax 4WD (SIDI)', '300', '300 AWD', 'Grand Caravan', 'Pacifica',
       'Pacifica AWD', 'Challenger', 'Challenger (MDS)', 'Challenger AWD',
       'Challenger Widebody (MDS)', 'Challenger Widebody',
       'Challenger SRT Hellcat', 'Challenger SRT Hellcat Widebody',
       'Charger', 'Charger (MDS)', 'Charger AWD',
       'Charger Widebody (MDS)', 'Charger SRT Hellcat Widebody',
       'Durango AWD', 'Durango AWD SRT', 'Durango AWD SRT Hellcat',
       '500X AWD', 'Bronco 4WD', 'Bronco Badlands 4WD',
       'Bronco Black Diamond 4WD', 'Bronco Sasquatch 4WD',
       'Bronco Sport 4WD', 'EcoSport', 'EcoSport AWD', 'Edge', 'Edge AWD',
       'Escape', 'Escape AWD', 'Escape Hybrid', 'Escape Hybrid AWD',
       'Expedition 4X4', 'Expedition MAX 4X4', 'Explorer AWD',
       'Explorer Timberline AWD', 'Explorer Hybrid AWD', 'F-150',
       'F-150 FFV', 'F-150 FFV (Without Stop-Start)', 'F-150 4X4',
       'F-150 4X4 (Without Stop-Start)', 'F-150 FFV 4X4',
       'F-150 FFV 4X4 (Without Stop-Start)', 'F-150 Raptor 4X4',
       'F-150 Raptor 4X4 (Without Stop-Start)', 'F-150 Raptor 37 4X4',
       'F-150 Raptor 37 4X4 (Without Stop-Start)', 'F-150 Tremor 4X4',
       'F-150 Tremor 4X4 (Without Stop-Start)', 'F-150 Hybrid',
       'F-150 Hybrid 4X4', 'GT', 'Mustang', 'Mustang (High Performance)',
       'Mustang Convertible', 'Mustang Convertible (High Performance)',
       'Mustang Mach 1', 'Ranger 4WD', 'Ranger 4WD Tremor',
       'Shelby GT500 Mustang', 'T-150 Wagon FFV', 'T-150 Wagon FFV 4WD',
       'Transit Connect Van', 'Transit Connect Van FFV',
       'Transit Connect Wagon LWB', 'Transit Connect Wagon LWB FFV',
       'G70', 'G70 AWD', 'G80 AWD', 'G90 AWD', 'GV80 AWD', 'Acadia',
       'Acadia AWD', 'Canyon', 'Canyon 4WD', 'Sierra', 'Sierra WT',
       'Sierra (Without AFM)', 'Sierra FFV', 'Sierra (Without DFM)',
       'Sierra 4WD', 'Sierra 4WD WT', 'Sierra 4WD AT4',
       'Sierra 4WD (Without AFM)', 'Sierra 4WD FFV',
       'Sierra 4WD (Without DFM)', 'Sierra 4WD AT4 (Without DFM)',
       'Sierra 4WD (Without Stop-Start)',
       'Sierra 4WD AT4 (Without Stop-Start)', 'Terrain', 'Terrain AWD',
       'Yukon', 'Yukon (Without Stop-Start)', 'Yukon 4WD',
       'Yukon 4WD (Without Stop-Start)', 'Yukon XL',
       'Yukon XL (Without Stop-Start)', 'Yukon XL 4WD',
       'Yukon XL 4WD (Without Stop-Start)', 'Accord',
       'Accord Sport/Touring', 'Accord Hybrid',
       'Accord Hybrid Sport/Touring', 'Civic Hatchback',
       'Civic Hatchback Sport', 'Civic Sedan', 'Civic Type R', 'CR-V',
       'CR-V AWD', 'HR-V', 'HR-V AWD', 'Insight EX', 'Insight Touring',
       'Odyssey', 'Passport AWD', 'Pilot AWD', 'Ridgeline AWD', 'Elantra',
       'Elantra (ISG)', 'Elantra Hybrid Blue', 'IONIQ', 'IONIQ Blue',
       'Kona', 'Kona AWD', 'Palisade', 'Palisade AWD', 'Santa Fe',
       'Santa Fe AWD', 'Santa Fe Hybrid', 'Sonata', 'Sonata Hybrid',
       'Tucson', 'Tucson AWD', 'Veloster N', 'Venue', 'Q50 AWD',
       'Q50 AWD Red Sport', 'Q60 AWD', 'Q60 AWD Red Sport', 'QX50 AWD',
       'QX80 4WD', 'F-TYPE P300 Convertible', 'F-TYPE P300 Coupe',
       'F-TYPE P380 AWD Convertible', 'F-TYPE P380 AWD Coupe',
       'F-TYPE R AWD Convertible', 'F-TYPE R AWD Coupe', 'Cherokee',
       'Cherokee 4X4 Active Drive I', 'Cherokee 4X4 Active Drive II',
       'Cherokee 4X4 Active Drive Lock', 'Compass', 'Compass 4X4',
       'Gladiator 4X4 EcoDiesel', 'Gladiator 4X4 Rubicon EcoDiesel',
       'Gladiator 4X4', 'Grand Cherokee 4X4', 'Grand Cherokee 4X4 SRT',
       'Grand Cherokee 4X4 Trackhawk', 'Grand Cherokee L 4X4', 'Renegade',
       'Renegade 4X4', 'Renegade 4X4 Trailhawk', 'Wrangler JL 4X4',
       'Wrangler JL 4X4 eTorque', 'Wrangler JL Unlimited 4X4',
       'Wrangler JL Unlimited 4X4 EcoDiesel',
       'Wrangler JL Unlimited 4X4 Rubicon EcoDiesel',
       'Wrangler JL Unlimited 4X4 eTorque', 'Forte', 'Forte 5', 'K5',
       'K5 AWD', 'Niro', 'Niro FE', 'Niro Touring', 'Rio', 'Sedona',
       'Seltos', 'Seltos AWD', 'Sorento AWD', 'Soul', 'Sportage',
       'Sportage AWD', 'Stinger AWD', 'Telluride AWD',
       'Aventador Coupe S', 'Aventador Coupe SVJ', 'Aventador Roadster S',
       'Aventador Roadster SVJ', 'Huracan', 'Huracan AWD',
       'Huracan Spyder', 'Huracan Spyder AWD', 'Urus', 'ES 250 AWD',
       'ES 300h', 'ES 350', 'ES 350 F SPORT', 'GX 460', 'IS 300',
       'IS 300 AWD', 'IS 350 AWD', 'LC 500', 'LC 500 Convertible',
       'LC 500h', 'LS 500 AWD', 'LS 500h AWD', 'LX 570', 'NX 300 AWD',
       'NX 300 AWD F SPORT', 'NX 300h AWD', 'RC 300 AWD', 'RC 350 AWD',
       'RC F', 'RX 350 AWD', 'RX 350 L AWD', 'RX 450h AWD',
       'RX 450h L AWD', 'UX 200', 'UX 250h', 'UX 250h AWD', 'Aviator AWD',
       'Corsair AWD', 'Nautilus AWD', 'Navigator 4X4', 'Ghibli',
       'Ghibli S', 'Ghibli S Q4', 'Ghibli Trofeo', 'Levante', 'Levante S',
       'Levante GTS', 'Levante Trofeo', 'Quattroporte S',
       'Quattroporte S Q4', 'Quattroporte Trofeo', 'CX-3', 'CX-3 (SIL)',
       'CX-3 4WD', 'CX-30', 'CX-30 4WD', 'CX-30 Turbo 4WD', 'CX-5',
       'CX-5 (Cylinder Deactivation)', 'CX-5 4WD',
       'CX-5 4WD (Cylinder Deactivation)', 'CX-5 Turbo 4WD', 'CX-9 4WD',
       'Mazda3 4-Door', 'Mazda3 4-Door (SIL)', 'Mazda3 4-Door 4WD',
       'Mazda3 4-Door Turbo 4WD', 'Mazda3 5-Door', 'Mazda3 5-Door (SIL)',
       'Mazda3 5-Door 4WD', 'Mazda3 5-Door Turbo 4WD', 'Mazda6',
       'Mazda6 Turbo', 'MX-5', 'MX-5 (SIL)', 'A 220 4MATIC Sedan',
       'A 250 4MATIC Hatch', 'AMG A 35 4MATIC Sedan',
       'AMG A 35 4MATIC Hatch', 'AMG C 43 4MATIC Sedan',
       'AMG C 43 4MATIC Cabriolet', 'AMG C 43 4MATIC Coupe',
       'AMG C 43 4MATIC Wagon', 'AMG C 63 Sedan', 'AMG C 63 S Sedan',
       'AMG C 63 S Cabriolet', 'AMG C 63 S Coupe',
       'AMG CLA 35 4MATIC Coupe', 'AMG CLA 45 4MATIC Coupe',
       'AMG CLS 53 4MATIC+ Coupe', 'AMG E 53 4MATIC+ Sedan',
       'AMG E 53 4MATIC+ Cabriolet', 'AMG E 53 4MATIC+ Coupe',
       'AMG E 53 4MATIC+ Wagon', 'AMG E 63 S 4MATIC+ Sedan',
       'AMG E 63 S 4MATIC+ Wagon', 'AMG G 63 SUV',
       'AMG GLA 35 4MATIC SUV', 'AMG GLA 45 4MATIC SUV', 'AMG GLB 35 SUV',
       'AMG GLC 43 4MATIC SUV', 'AMG GLC 43 4MATIC Coupe',
       'AMG GLC 63 S 4MATIC+ SUV', 'AMG GLC 63 S 4MATIC+ Coupe',
       'AMG GLE 53 4MATIC+ SUV', 'AMG GLE 53 4MATIC+ Coupe',
       'AMG GLE 63 S 4MATIC+ SUV', 'AMG GLE 63 S 4MATIC+ Coupe',
       'AMG GLS 63 4MATIC+ SUV', 'AMG GT 53 4MATIC+ Coupe',
       'AMG GT 63 4MATIC+ Coupe', 'AMG GT 63 S 4MATIC+ Coupe',
       'AMG GT Black Series Coupe', 'AMG GT C Coupe', 'AMG GT C Roadster',
       'AMG GT R Coupe', 'AMG S 63 4MATIC+ Cabriolet',
       'AMG S 63 4MATIC+ Coupe', 'C 300 4MATIC Sedan',
       'C 300 4MATIC Cabriolet', 'C 300 4MATIC Coupe',
       'C 300 4MATIC Wagon', 'CLA 250 4MATIC Coupe',
       'CLS 450 4MATIC Coupe', 'E 350 4MATIC Sedan', 'E 450 4MATIC Sedan',
       'E 450 4MATIC Cabriolet', 'E 450 4MATIC Coupe',
       'E 450 4MATIC All-Terrain Wagon', 'G 550 SUV',
       'GLA 250 4MATIC SUV', 'GLB 250 4MATIC SUV', 'GLC 300 4MATIC SUV',
       'GLC 300 4MATIC Coupe', 'GLE 350 4MATIC SUV', 'GLE 450 4MATIC SUV',
       'GLS 450 4MATIC SUV', 'GLS 580 4MATIC SUV',
       'Maybach GLS 600 4MATIC SUV', 'Maybach S 580 4MATIC Sedan',
       'Metris Cargo Van', 'Metris Cargo Van LWB', 'Metris Passenger Van',
       'S 500 4MATIC SWB Sedan', 'S 560 Cabriolet', 'S 560 4MATIC Coupe',
       'S 580 4MATIC LWB Sedan', 'Cooper 3 Door', 'Cooper 5 Door',
       'Cooper Clubman ALL4', 'Cooper Convertible',
       'Cooper Countryman ALL4', 'Cooper S 3 Door', 'Cooper S 5 Door',
       'Cooper S Clubman ALL4', 'Cooper S Convertible',
       'Cooper S Countryman ALL4', 'John Cooper Works 3 Door',
       'John Cooper Works Clubman ALL4', 'John Cooper Works Convertible',
       'John Cooper Works Countryman ALL4', 'John Cooper Works GP',
       'Mirage', 'RVR', 'RVR 4WD', 'Altima AWD', 'Altima AWD SR/Platinum',
       'Armada 4WD', 'GT-R', 'Kicks', 'Maxima', 'Murano', 'Murano AWD',
       'NV200 Cargo Van', 'Qashqai', 'Qashqai AWD', 'Rogue', 'Rogue AWD',
       'Sentra', 'Sentra SR', 'Titan 4WD', 'Titan 4WD Pro-4X', 'Versa',
       '718 Boxster', '718 Boxster GTS 4.0', '718 Boxster S',
       '718 Boxster T', '718 Cayman', '718 Cayman GT4',
       '718 Cayman GTS 4.0', '718 Cayman S', '718 Cayman T', '718 Spyder',
       '911 Carrera', '911 Carrera Cabriolet', '911 Carrera S',
       '911 Carrera S Cabriolet', '911 Carrera 4',
       '911 Carrera 4 Cabriolet', '911 Carrera 4S',
       '911 Carrera 4S Cabriolet', '911 Targa 4', '911 Targa 4S',
       '911 Turbo', '911 Turbo Cabriolet', '911 Turbo S',
       '911 Turbo S Cabriolet', 'Cayenne', 'Cayenne Coupe', 'Cayenne GTS',
       'Cayenne GTS Coupe', 'Cayenne S', 'Cayenne S Coupe',
       'Cayenne Turbo', 'Cayenne Turbo Coupe', 'Macan', 'Macan GTS',
       'Macan S', 'Macan Turbo', 'Panamera', 'Panamera 4',
       'Panamera 4 Executive', 'Panamera 4 ST', 'Panamera 4S',
       'Panamera 4S Executive', 'Panamera 4S ST', 'Panamera GTS',
       'Panamera GTS ST', 'Panamera Turbo S',
       'Panamera Turbo S Executive', 'Panamera Turbo S ST',
       '1500 EcoDiesel', '1500 HFE EcoDiesel', '1500 eTorque',
       '1500 HFE eTorque', '1500', '1500 4X4 EcoDiesel',
       '1500 4X4 eTorque', '1500 4X4', '1500 4X4 TRX', '1500 Classic',
       '1500 Classic 4X4', 'ProMaster City', 'Cullinan',
       'Cullinan Black Badge', 'Dawn', 'Dawn Black Badge', 'Ghost',
       'Ghost EWB', 'Phantom', 'Phantom EWB', 'Wraith',
       'Wraith Black Badge', 'Ascent AWD', 'Crosstrek AWD',
       'Forester AWD', 'Impreza 4-Door AWD', 'Impreza 5-Door AWD',
       'Legacy AWD', 'Outback AWD', 'WRX AWD', 'WRX STI AWD',
       '4Runner 4WD', '4Runner 4WD (Part-Time 4WD)', 'Avalon',
       'Avalon AWD', 'C-HR', 'Camry LE/SE', 'Camry XLE/XSE', 'Camry',
       'Camry XSE', 'Camry TRD', 'Camry AWD LE/SE', 'Camry AWD XLE/XSE',
       'Camry Hybrid LE', 'Camry Hybrid SE/XLE/XSE', 'Corolla',
       'Corolla XLE', 'Corolla XSE', 'Corolla Apex Edition',
       'Corolla Hatchback', 'Corolla Hybrid', 'GR Supra 2.0',
       'GR Supra 3.0', 'Highlander', 'Highlander AWD',
       'Highlander Hybrid AWD', 'Highlander Hybrid AWD Limited/Platinum',
       'Prius', 'Prius AWD', 'RAV4', 'RAV4 (Stop/Start)', 'RAV4 AWD',
       'RAV4 AWD (Stop/Start)', 'RAV4 AWD LE', 'RAV4 AWD TRD Off-Road',
       'RAV4 Hybrid AWD', 'Sequoia 4WD', 'Sienna', 'Sienna AWD',
       'Tacoma 4WD', 'Tacoma 4WD D-Cab TRD Off-Road/PRO', 'Tundra',
       'Tundra 4WD', 'Venza AWD', 'Arteon 4MOTION', 'Atlas 4MOTION',
       'Atlas Cross Sport 4MOTION', 'Golf', 'Golf GTI', 'Jetta',
       'Jetta GLI', 'Passat', 'Tiguan', 'Tiguan 4MOTION', 'S60 T5',
       'S60 T5 AWD', 'S60 T6 AWD', 'S90 T6 AWD', 'V60 T5', 'V60 T6 AWD',
       'V60 CC T5 AWD', 'XC40 T4 AWD', 'XC40 T5 AWD', 'XC60 T5 AWD',
       'XC60 T6 AWD', 'XC90 T5 AWD', 'XC90 T6 AWD'], dtype=object)

In [10]:
df['Vehicle_Class'].value_counts()

Vehicle_Class
SUV: Small                 192
SUV: Standard              127
Pickup truck: Standard     115
Mid-size                   114
Compact                     83
Subcompact                  83
Full-size                   65
Two-seater                  56
Minicompact                 30
Station wagon: Small        20
Pickup truck: Small         17
Special purpose vehicle     13
Station wagon: Mid-size      9
Minivan                      7
Van: Passenger               4
Name: count, dtype: int64

### Drop columns

In [11]:
df = df.drop(columns = ["Model_Year", "Model"])

### Define num & obj columns

In [12]:
numerical_columns = df.select_dtypes(include=['number'])
numerical_columns

,Engine_Size,Cylinders,Fuel_Consumption_in_City(L/100 km),Fuel_Consumption_in_City_Hwy(L/100 km),Fuel_Consumption_comb(L/100km),CO2_Emissions,Smog_Level
0,2.4,4,9.9,7.0,8.6,199,3
1,3.5,6,11.1,10.8,11.0,256,3
2,2.0,4,11.0,8.6,9.9,232,6
3,2.0,4,11.3,9.1,10.3,242,6
4,2.0,4,11.2,8.0,9.8,230,7
...,...,...,...,...,...,...,...
930,2.0,4,10.7,7.7,9.4,219,5
931,2.0,4,11.1,8.3,9.9,230,5
932,2.0,4,11.7,8.6,10.3,240,7
933,2.0,4,11.5,8.4,10.1,236,5
934,2.0,4,12.1,8.5,10.5,245,7

In [13]:
object_columns = df.select_dtypes(include=['object'])
object_columns

      Make  Vehicle_Class Transmission
0    Acura        Compact          AM8
1    Acura     Two-seater          AM9
2    Acura     SUV: Small         AS10
3    Acura     SUV: Small         AS10
4    Acura        Compact         AS10
..     ...            ...          ...
930  Volvo     SUV: Small          AS8
931  Volvo     SUV: Small          AS8
932  Volvo     SUV: Small          AS8
933  Volvo  SUV: Standard          AS8
934  Volvo  SUV: Standard          AS8

[935 rows x 3 columns]

In [14]:
unique_vehicle_classes = df['Vehicle_Class'].unique()
print("Unique Vehicle Classes:", unique_vehicle_classes)

Unique Vehicle Classes: ['Compact' 'Two-seater' 'SUV: Small' 'Mid-size' 'Minicompact'
 'SUV: Standard' 'Station wagon: Small' 'Subcompact'
 'Station wagon: Mid-size' 'Full-size' 'Pickup truck: Small'
 'Pickup truck: Standard' 'Minivan' 'Van: Passenger'
 'Special purpose vehicle']

In [18]:
# Define a mapping function for vehicle classes
def classify_vehicle(vehicle_class):
    if vehicle_class in ['Compact', 'Subcompact', 'Minicompact']:
        return 'Compact Cars'
    elif vehicle_class == 'Two-seater':
        return 'Luxury and Sport Vehicles'
    elif vehicle_class == 'SUV: Small':
        return 'Small SUVs'
    elif vehicle_class in ['SUV: Standard', 'Mid-size', 'Full-size']:
        return 'Standard and Full-size SUVs'
    else:
        return 'Other/Unclassified'

# Apply the classification function to each row in the DataFrame
df['New_Class'] = df['Vehicle_Class'].apply(classify_vehicle)

# Display the updated DataFrame
df

,Make,Vehicle_Class,Engine_Size,Cylinders,Transmission,Fuel_Consumption_in_City(L/100 km),Fuel_Consumption_in_City_Hwy(L/100 km),Fuel_Consumption_comb(L/100km),CO2_Emissions,Smog_Level,New_Class
0,Acura,Compact,2.4,4,AM8,9.9,7.0,8.6,199,3,Compact Cars
1,Acura,Two-seater,3.5,6,AM9,11.1,10.8,11.0,256,3,Luxury and Sport Vehicles
2,Acura,SUV: Small,2.0,4,AS10,11.0,8.6,9.9,232,6,Small SUVs
3,Acura,SUV: Small,2.0,4,AS10,11.3,9.1,10.3,242,6,Small SUVs
4,Acura,Compact,2.0,4,AS10,11.2,8.0,9.8,230,7,Compact Cars
...,...,...,...,...,...,...,...,...,...,...,...
930,Volvo,SUV: Small,2.0,4,AS8,10.7,7.7,9.4,219,5,Small SUVs
931,Volvo,SUV: Small,2.0,4,AS8,11.1,8.3,9.9,230,5,Small SUVs
932,Volvo,SUV: Small,2.0,4,AS8,11.7,8.6,10.3,240,7,Small SUVs
933,Volvo,SUV: Standard,2.0,4,AS8,11.5,8.4,10.1,236,5,Standard and Full-size SUVs
934,Volvo,SUV: Standard,2.0,4,AS8,12.1,8.5,10.5,245,7,Standard and Full-size SUVs

In [20]:
# Print unique values in the Vehicle_Class column before mapping
print("Unique Vehicle Classes before mapping:", df['Vehicle_Class'].unique())

# Define a mapping function for vehicle classes
def classify_vehicle(vehicle_class):
    if vehicle_class in ['Compact', 'Subcompact', 'Minicompact']:
        return 'Compact Cars'
    elif vehicle_class == 'Two-seater':
        return 'Luxury and Sport Vehicles'
    elif vehicle_class == 'SUV: Small':
        return 'Small SUVs'
    elif vehicle_class in ['SUV: Standard', 'Mid-size', 'Full-size']:
        return 'Standard and Full-size SUVs'
    else:
        return 'Other/Unclassified'

# Apply the classification function to each row in the DataFrame
df['New_Class'] = df['Vehicle_Class'].apply(classify_vehicle)

# Print unique values in the New_Class column after mapping
print("Unique New Classes after mapping:", df['New_Class'].unique())

# Display the updated DataFrame
print(df)

Unique Vehicle Classes before mapping: ['Compact' 'Two-seater' 'SUV: Small' 'Mid-size' 'Minicompact'
 'SUV: Standard' 'Station wagon: Small' 'Subcompact'
 'Station wagon: Mid-size' 'Full-size' 'Pickup truck: Small'
 'Pickup truck: Standard' 'Minivan' 'Van: Passenger'
 'Special purpose vehicle']
Unique New Classes after mapping: ['Compact Cars' 'Luxury and Sport Vehicles' 'Small SUVs'
 'Standard and Full-size SUVs' 'Other/Unclassified']
      Make  Vehicle_Class  Engine_Size  Cylinders Transmission  \
0    Acura        Compact          2.4          4          AM8
1    Acura     Two-seater          3.5          6          AM9
2    Acura     SUV: Small          2.0          4         AS10
3    Acura     SUV: Small          2.0          4         AS10
4    Acura        Compact          2.0          4         AS10
..     ...            ...          ...        ...          ...
930  Volvo     SUV: Small          2.0          4          AS8
931  Volvo     SUV: Small          2.0          4          AS8
932  Volvo     SUV: Small          2.0          4          AS8
933  Volvo  SUV: Standard          2.0          4          AS8
934  Volvo  SUV: Standard          2.0          4          AS8

     Fuel_Consumption_in_City(L/100 km)  \
0                                   9.9
1                                  11.1
2                                  11.0
3                                  11.3
4                                  11.2
..                                  ...
930                                10.7
931                                11.1
932                                11.7
933                                11.5
934                                12.1

     Fuel_Consumption_in_City_Hwy(L/100 km)  Fuel_Consumption_comb(L/100km)  \
0                                       7.0                             8.6
1                                      10.8                            11.0
2                                       8.6                             9.9
3                                       9.1                            10.3
4                                       8.0                             9.8
..                                      ...                             ...
930                                     7.7                             9.4
931                                     8.3                             9.9
932                                     8.6                            10.3
933                                     8.4                            10.1
934                                     8.5                            10.5

     CO2_Emissions  Smog_Level                    New_Class
0              199           3                 Compact Cars
1              256           3    Luxury and Sport Vehicles
2              232           6                   Small SUVs
3              242           6                   Small SUVs
4              230           7                 Compact Cars
..             ...         ...                          ...
930            219           5                   Small SUVs
931            230           5                   Small SUVs
932            240           7                   Small SUVs
933            236           5  Standard and Full-size SUVs
934            245           7  Standard and Full-size SUVs

[935 rows x 11 columns]

Splitting the transmission into two columns

In [23]:
# Function to extract transmission type
def extract_transmission_type(trans):
    return ''.join([char for char in trans if char.isalpha()])

# Function to extract number of gears
def extract_number_of_gears(trans):
    return ''.join([char for char in trans if char.isdigit()])

# Apply the functions to create new columns
df['Transmission_Type'] = df['Transmission'].apply(extract_transmission_type)
df['Number_of_Gears'] = df['Transmission'].apply(extract_number_of_gears)

# Display the updated DataFrame
print(df)

      Make  Vehicle_Class  Engine_Size  Cylinders Transmission  \
0    Acura        Compact          2.4          4          AM8
1    Acura     Two-seater          3.5          6          AM9
2    Acura     SUV: Small          2.0          4         AS10
3    Acura     SUV: Small          2.0          4         AS10
4    Acura        Compact          2.0          4         AS10
..     ...            ...          ...        ...          ...
930  Volvo     SUV: Small          2.0          4          AS8
931  Volvo     SUV: Small          2.0          4          AS8
932  Volvo     SUV: Small          2.0          4          AS8
933  Volvo  SUV: Standard          2.0          4          AS8
934  Volvo  SUV: Standard          2.0          4          AS8

     Fuel_Consumption_in_City(L/100 km)  \
0                                   9.9
1                                  11.1
2                                  11.0
3                                  11.3
4                                  11.2
..                                  ...
930                                10.7
931                                11.1
932                                11.7
933                                11.5
934                                12.1

     Fuel_Consumption_in_City_Hwy(L/100 km)  Fuel_Consumption_comb(L/100km)  \
0                                       7.0                             8.6
1                                      10.8                            11.0
2                                       8.6                             9.9
3                                       9.1                            10.3
4                                       8.0                             9.8
..                                      ...                             ...
930                                     7.7                             9.4
931                                     8.3                             9.9
932                                     8.6                            10.3
933                                     8.4                            10.1
934                                     8.5                            10.5

     CO2_Emissions  Smog_Level                    New_Class Transmission_Type  \
0              199           3                 Compact Cars                AM
1              256           3    Luxury and Sport Vehicles                AM
2              232           6                   Small SUVs                AS
3              242           6                   Small SUVs                AS
4              230           7                 Compact Cars                AS
..             ...         ...                          ...               ...
930            219           5                   Small SUVs                AS
931            230           5                   Small SUVs                AS
932            240           7                   Small SUVs                AS
933            236           5  Standard and Full-size SUVs                AS
934            245           7  Standard and Full-size SUVs                AS

    Number_of_Gears
0                 8
1                 9
2                10
3                10
4                10
..              ...
930               8
931               8
932               8
933               8
934               8

[935 rows x 13 columns]

In [24]:
df

,Make,Vehicle_Class,Engine_Size,Cylinders,Transmission,Fuel_Consumption_in_City(L/100 km),Fuel_Consumption_in_City_Hwy(L/100 km),Fuel_Consumption_comb(L/100km),CO2_Emissions,Smog_Level,New_Class,Transmission_Type,Number_of_Gears
0,Acura,Compact,2.4,4,AM8,9.9,7.0,8.6,199,3,Compact Cars,AM,8
1,Acura,Two-seater,3.5,6,AM9,11.1,10.8,11.0,256,3,Luxury and Sport Vehicles,AM,9
2,Acura,SUV: Small,2.0,4,AS10,11.0,8.6,9.9,232,6,Small SUVs,AS,10
3,Acura,SUV: Small,2.0,4,AS10,11.3,9.1,10.3,242,6,Small SUVs,AS,10
4,Acura,Compact,2.0,4,AS10,11.2,8.0,9.8,230,7,Compact Cars,AS,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
930,Volvo,SUV: Small,2.0,4,AS8,10.7,7.7,9.4,219,5,Small SUVs,AS,8
931,Volvo,SUV: Small,2.0,4,AS8,11.1,8.3,9.9,230,5,Small SUVs,AS,8
932,Volvo,SUV: Small,2.0,4,AS8,11.7,8.6,10.3,240,7,Small SUVs,AS,8
933,Volvo,SUV: Standard,2.0,4,AS8,11.5,8.4,10.1,236,5,Standard and Full-size SUVs,AS,8
934,Volvo,SUV: Standard,2.0,4,AS8,12.1,8.5,10.5,245,7,Standard and Full-size SUVs,AS,8

In [25]:
df = df.drop(columns=['Transmission'])

In [26]:
df

,Make,Vehicle_Class,Engine_Size,Cylinders,Fuel_Consumption_in_City(L/100 km),Fuel_Consumption_in_City_Hwy(L/100 km),Fuel_Consumption_comb(L/100km),CO2_Emissions,Smog_Level,New_Class,Transmission_Type,Number_of_Gears
0,Acura,Compact,2.4,4,9.9,7.0,8.6,199,3,Compact Cars,AM,8
1,Acura,Two-seater,3.5,6,11.1,10.8,11.0,256,3,Luxury and Sport Vehicles,AM,9
2,Acura,SUV: Small,2.0,4,11.0,8.6,9.9,232,6,Small SUVs,AS,10
3,Acura,SUV: Small,2.0,4,11.3,9.1,10.3,242,6,Small SUVs,AS,10
4,Acura,Compact,2.0,4,11.2,8.0,9.8,230,7,Compact Cars,AS,10
...,...,...,...,...,...,...,...,...,...,...,...,...
930,Volvo,SUV: Small,2.0,4,10.7,7.7,9.4,219,5,Small SUVs,AS,8
931,Volvo,SUV: Small,2.0,4,11.1,8.3,9.9,230,5,Small SUVs,AS,8
932,Volvo,SUV: Small,2.0,4,11.7,8.6,10.3,240,7,Small SUVs,AS,8
933,Volvo,SUV: Standard,2.0,4,11.5,8.4,10.1,236,5,Standard and Full-size SUVs,AS,8
934,Volvo,SUV: Standard,2.0,4,12.1,8.5,10.5,245,7,Standard and Full-size SUVs,AS,8

In [ ]:
# tstr